[platformio]
default_envs = 12KSG02LP1_v3
src_dir = firmware

[env]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_ldf_mode = chain+
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
lib_deps =
    lvgl/lvgl@8.4.0
    moononournation/GFX Library for Arduino@1.4.7
    bblanchon/ArduinoJson@6.21.5
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE

[env:12KSG02LP1_v3]
build_src_filter = -<*> +<DEYE_V3/main.cpp>
build_unflags = -std=gnu++11
build_flags =
    ${env.build_flags}
    -std=gnu++17
    -Ifirmware/DEYE_V3
    -include firmware/DEYE_V3/lv_conf.h

[env:deye_vetronic]
build_src_filter = -<*> +<DEYE_VETRONIC/main.cpp>
build_flags =
    ${env.build_flags}
    -Ifirmware/DEYE_VETRONIC
    -include firmware/DEYE_VETRONIC/lv_conf.h
